### ISSUE TITLE
No build script or dist available?

### ISSUE THREAD

**Issue by Nedlinin** [IOT-DSA/sdk-dslink-javascript#3]
There doesn't appear to be a build script in the repo that the README mentions nor a dist folder.

What are the current build options?

**Comment by mbullington** [comment]
Hello! 

Sorry for the long delay, I thought that I had responded to your queries quite a while ago.

Anyways, the new version of the SDK is maintained on the new-sdk branch. To build it, you need to have the Dart SDK installed, and grinder globally installed from pub. Then, run either `grind node` or `grind browser` to get the respective builds.

You shouldn't need to do this, as our build system takes care of all of this, and pushes builds to the artifacts branch as well. As for adding this branch to your package.json, there is an example (along with how to properly use the JavaScript SDK) here. 

https://github.com/IOT-DSA/template-dslink-javascript

```
"dependencies": {
  "dslink": "IOT-DSA/sdk-dslink-javascript#artifacts"
}
```

The dslink package will also be published on npm very soon, so you'll be able to use it using all built-ins from npm.

Hope this answers all questions you may have about building the JavaScript SDK for DSA, feel free to ask any more questions you may have, and I'll personally get back to you in a timely fashion.
